import { createHash } from 'crypto';
import { assertRangedString } from '.';

export const len0 = assertRangedString('');
export const len1 = assertRangedString('-');
export const len2 = assertRangedString('--');
export const len3 = assertRangedString('---');
export const len4 = assertRangedString('----');
export const len5 = assertRangedString('-----');
export const len6 = assertRangedString('------');
export const len7 = assertRangedString('-------');
export const len8 = assertRangedString('--------');
export const len9 = assertRangedString('---------');
export const len10 = assertRangedString('----------');
export const len11 = assertRangedString('-----------');
export const len12 = assertRangedString('------------');
export const len13 = assertRangedString('-------------');
export const len14 = assertRangedString('--------------');
export const len15 = assertRangedString('---------------');
export const len16 = assertRangedString('----------------');
export const len17 = assertRangedString('-----------------');
export const len18 = assertRangedString('------------------');
export const len19 = assertRangedString('-------------------');
export const len20 = assertRangedString('--------------------');
export const len21 = assertRangedString('---------------------');
export const len22 = assertRangedString('----------------------');
export const len23 = assertRangedString('-----------------------');
export const len24 = assertRangedString('------------------------');
export const len25 = assertRangedString('-------------------------');
export const len26 = assertRangedString('--------------------------');
export const len27 = assertRangedString('---------------------------');
export const len28 = assertRangedString('----------------------------');
export const len29 = assertRangedString('-----------------------------');
export const len30 = assertRangedString('------------------------------');
export const len31 = assertRangedString('-------------------------------');
export const len32 = assertRangedString('--------------------------------');
export type RangedString0 = typeof len0;
export type RangedString1 = typeof len1;
export type RangedString2 = typeof len2;
export type RangedString3 = typeof len3;
export type RangedString4 = typeof len4;
export type RangedString5 = typeof len5;
export type RangedString6 = typeof len6;
export type RangedString7 = typeof len7;
export type RangedString8 = typeof len8;
export type RangedString9 = typeof len9;
export type RangedString10 = typeof len10;
export type RangedString11 = typeof len11;
export type RangedString12 = typeof len12;
export type RangedString13 = typeof len13;
export type RangedString14 = typeof len14;
export type RangedString15 = typeof len15;
export type RangedString16 = typeof len16;
export type RangedString17 = typeof len17;
export type RangedString18 = typeof len18;
export type RangedString19 = typeof len19;
export type RangedString20 = typeof len20;
export type RangedString21 = typeof len21;
export type RangedString22 = typeof len22;
export type RangedString23 = typeof len23;
export type RangedString24 = typeof len24;
export type RangedString25 = typeof len25;
export type RangedString26 = typeof len26;
export type RangedString27 = typeof len27;
export type RangedString28 = typeof len28;
export type RangedString29 = typeof len29;
export type RangedString30 = typeof len30;
export type RangedString31 = typeof len31;
export type RangedString32 = typeof len32;

export const getHash6 = (s: string): RangedString6 => {
  const hash = createHash('RSA-SHA1');
  hash.update(s);
  const hash6 = hash.digest().toString('hex').slice(0, 6) as RangedString6;
  return hash6;
};
