import type { PolicySet } from '@self/def-manager/src/stack/policies/dev/types';
import { RESOURCE_DEV_SHORT_PREFIX } from '@self/shared/lib/const';

export const devRdsPolicy = (ac: string): PolicySet => ({
  allowResources: [
    // `arn:aws:rds:*:${ac}:cluster-pg:*`,
    `arn:aws:rds:*:${ac}:snapshot:${RESOURCE_DEV_SHORT_PREFIX}*`,
    // `arn:aws:rds:*:${ac}:db-proxy-endpoint:*`,
    `arn:aws:rds:*:${ac}:db:${RESOURCE_DEV_SHORT_PREFIX}*`,
    // `arn:aws:rds:*:${ac}:es:*`,
    // `arn:aws:rds:*:${ac}:db-proxy:*`,
    // `arn:aws:rds:*:${ac}:target-group:*`,
    // `arn:aws:rds:*:${ac}:cluster-snapshot:*`,
    // `arn:aws:rds:*:${ac}:pg:*`,
    // `arn:aws:rds:*:${ac}:ri:*`,
    // `arn:aws:rds:*:${ac}:cluster:*`,
    // `arn:aws:rds:*:${ac}:og:*`,
    // `arn:aws:rds:*:${ac}:cev:*/*/*`,
    `arn:aws:rds:*:${ac}:secgrp:${RESOURCE_DEV_SHORT_PREFIX}*`,
    // `arn:aws:rds:*:${ac}:cluster-endpoint:*`,
    // `arn:aws:rds::${ac}:global-cluster:*`,
    `arn:aws:rds:*:${ac}:subgrp:${RESOURCE_DEV_SHORT_PREFIX}*`,
  ],
  allowActions: [
    // "rds:ModifyRecommendation",
    // "rds:DeleteInstallationMedia",
    // "rds:CreateCustomAvailabilityZone",
    // 'rds:DescribeDBEngineVersions',
    // 'rds:CrossRegionCommunication',
    // 'rds:DescribeExportTasks',
    // 'rds:StartExportTask',
    // 'rds:DescribeEngineDefaultParameters',
    // 'rds:DescribeRecommendations',
    // 'rds:DescribeCustomAvailabilityZones',
    // 'rds:DescribeReservedDBInstancesOfferings',
    // "rds:DeleteCustomAvailabilityZone",
    // 'rds:ImportInstallationMedia',
    // 'rds:DescribeRecommendationGroups',
    // 'rds:DescribeSourceRegions',
    // 'rds:DescribeEngineDefaultClusterParameters',
    // 'rds:DescribeInstallationMedia',
    // "rds:CreateDBProxy",
    // 'rds:DescribeEventCategories',
    // 'rds:DescribeEvents',
    // "rds:CancelExportTask",
    // "rds:DeleteDBInstanceAutomatedBackup",
    // "rds:ModifyCertificates",
    // 'rds:DescribeOrderableDBInstanceOptions',
    // 'rds:DescribeCertificates',
    // 'rds:DescribeAccountAttributes',
  ],
  explicitDeny: [
    'rds:AddTagsToResource',
    'rds:RemoveTagsFromResource',

    'rds:Create*',
    'rds:Delete*',
    'rds:Modify*',
    'rds:Restore*',
  ],
});
